### ISSUE TITLE
Tags categorization and additions

### ISSUE THREAD

**Issue by raymondlui719** [raymondlui719/teamform-seed#12]
Brian, we should recognize & differentiate all tags and categorize them. Then we can let user choose which criteria they are looking at.
I have one more suggestion:
in team.html tag section, we can have some selection drop down to select the category, then we can add a drop down list and in this list, we add a search function like this:
http://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_js_dropdown_filter
Then the team leaders can easily add their tags they want.

**Comment by tsecheukyan1** [comment]
OK I will try. However, there are not much tags we can have, so maybe I will just do the category part, but not too necessary for the search function part.

**Comment by raymondlui719** [comment]
I think we don't have enough tags available because we are not only helping online user to form teams for university students or CS major students. So we need to find as more tags as possible
