### ISSUE TITLE
Delete event function of administrator

### ISSUE THREAD

**Issue by cflamad** [raymondlui719/teamform-seed#16]
As we discussed in #2, only the user who created the event has the permission to modify an event. It helps from errant users but another problem comes up which is other users cannot use the same event id to create their event once the event name has been used. Even the event is over, the administrator cannot release the event id to other users. So, do you think we should add "delete" under the admin page?

**Comment by raymondlui719** [comment]
Yes, we can add a terminate event button for the event admin in admin page
