### ISSUE TITLE
About the permissions of unauthorized users

### ISSUE THREAD

**Issue by cflamad** [raymondlui719/teamform-seed#2]
Is it possible to block people who have not logged-in yet from entering the admin/team/member pages? It is stranger that people can enter the page but showing nothing.

**Comment by raymondlui719** [comment]
I can disable the three buttons in the index.html if they are not logged in. Does it sound good?

**Comment by cflamad** [comment]
It's good. I found another problem that users who are not the event administrator but still can enter the admin page and modify the page. Would you want to block it also?

**Comment by raymondlui719** [comment]
How to determine who is the event admin?

**Comment by cflamad** [comment]
you can add a property holding the uid of the user who create the event.

**Comment by raymondlui719** [comment]
First issue solved
Will solve second issue in my next commit
