### ISSUE TITLE
Suggestion on invitation

### ISSUE THREAD

**Issue by cflamad** [raymondlui719/teamform-seed#23]
1. As a team leader may want to invite someone who have not joined the event. Can we invite people by using their email address? 
2. I think the invitation message is better to be shown on index.html, such that users can see the message once they have logged-in to the system.

**Comment by cycheungar** [comment]
1. How to implement that with email address?
2. I think that is a good idea. I will try to do it

**Comment by cflamad** [comment]
In team leader page, let the users input an email address. Then we search the corresponding user in database with the email. If we found the user, add the invitation to the user/user_id.
I believe that getting email addresses of each user is possible because all user login with facebook or email. @raymondlui719 can you save the email address to the database when an new user logged-in to the system?
