### ISSUE TITLE
How can I get the user name from Firebase

### ISSUE THREAD

**Issue by CarsonChow** [raymondlui719/teamform-seed#24]
I am currently working on the chatting board and I want to show the user name in front of the message. Do any one know a way to retrieve the data from Firebase?

**Comment by tsecheukyan1** [comment]
I think u can save the message itself and the user name of the message owner under one item, which makes retrieving it easier. For retrieving the data from Firebase, u can get some idea from the loadFunc in team.js

**Comment by cflamad** [comment]
Once you have a user id, you can call getUserWithId(user_id). You can get the name by obj.name where obj is the returned value of the function. You may want to have a look on getUserWithId under site.js

**Comment by cycheungar** [comment]
then what is the difference between the function retrieveNameFromID() and the method Andy suggested? because i used retrieveNameFromID().

**Comment by cflamad** [comment]
They are almost the same. retrieveNameFromID() searches $scope.users, which collected all the users related to the event when the page is being loaded, and returns the name once it found the user. getUserWithId() get the user (firebaseObject) from the database directly on demand.
