### ISSUE TITLE
Cannot get information from member/inTeam

### ISSUE THREAD

**Issue by cycheungar** [raymondlui719/teamform-seed#27]
I tried to stop team leader inviting users that are already in a team. however, i failed to get information from member/inTeam. how do i get it correctly?

**Comment by cflamad** [comment]
What do you mean by "failed to get information from member/inTeam"? If you get "undefined" when accessing inTeam property, the user probably has no team, otherwise he/she is in a team.

**Comment by cycheungar** [comment]
i mean i cannot find the correct path to a specific member/inTeam.
how do i get the correct path if i already have the member's id?

**Comment by cflamad** [comment]
firebase.database().ref(getURLParameter("q") + "/member/" + id).inTeam
P.S. getURLParameter("q") refers to the event name

**Comment by cycheungar** [comment]
if (firebase.database().ref(getURLParameter("q") + "/member/" + m).inTeam != null){
			window.alert("User is already in a team!");
}
I tried to check is inTeam null or not but it doesn't work. although there is data in inTeam, the alert is not executed. What's wrong?

**Comment by cflamad** [comment]
You should check if it is UNDEFINED. You can do it by
1. if (firebase.database().ref(getURLParameter("q") + "/member/" + id).inTeam) { ...}
2. if (typeof firebase.database().ref(getURLParameter("q") + "/member/" + id).inTeam == 'undefined') { ...}

**Comment by cycheungar** [comment]
It is not undefined because when i invite the user the first time, he is successfully invited and i can see the teamName saved in the user. When i invite the second time, it should pop the alert but it does't. Instead, it send the invitation again.
