### ISSUE TITLE
Problem of saving list of invitation

### ISSUE THREAD

**Issue by cycheungar** [raymondlui719/teamform-seed#31]
I tried to obtain the list of data in member/invitedBy but it does not work
`$scope.inviteList = $firebaseArray(firebase.database().ref(getURLParameter("q") + "/member/" + m + "invitedBy"));
			for (var i=0; i < $scope.inviteList.length; i++){
				$scope.param.invitedBy.push($scope.inviteList[i]);
			}`
Why?

**Comment by cflamad** [comment]
$scope.inviteList = $firebaseArray(firebase.database().ref(getURLParameter("q") + "/member/" + m + "invitedBy"));
$scope.inviteList.$loaded.then(function(list)) {
// your code});
list is the data you want to get. Try the above code to see if it works.
