### ISSUE TITLE
Tags for team and tags for member

### ISSUE THREAD

**Issue by cwwongau** [raymondlui719/teamform-seed#40]
As there are tags for both teams and members, would it be better to limit the tags available for weighted control by the team or by the members? Currently, there is no cap for members tags. Using member tags as the library for weighting is more difficult to manage for the team leader, and the effectiveness is not that great. However, current team tags are very limited and do not cover wide usage. I suggest changing the team tags into a similar format with member tags(addable by team leader), and only implement weighted control for tags supplied by the team leader. Would it be a good idea?

**Comment by cwwongau** [comment]
Tags for member would also be limited to tags supplied by team leaders (with the help of type ahead function) for easier and more practical team control.

**Comment by cflamad** [comment]
I think you should provide the same list of tag(under "tag" in firebase) to team leader as the weighted tag system are supposed to calculate the real weight based on the weighted assigned by team leader and the ability of the user. The ability of user is measured by the ability quiz which supposed to depend on the list of tags(i.e. one quiz for one tag Ideally). If you want to add more tags, I suggest you add them under the "tag" in firebase.

**Comment by cwwongau** [comment]
I understand your concern and the tags' compatibility with the quiz. However, the tags are just under the firebase instead of team based or event based, limiting the functionality of this application to CS related people. I suggest moving the "tag" under firebase under event or even teams to increase customizability. With common tags like male or female as a base.

**Comment by cflamad** [comment]
Actually the tags would not be limited to CS area as discussed in #12. You are welcome to add more tags outside CS area in the firebase (e.g. English skill, management skill...). However, if you let team leaders to have their own tags while we do not have the corresponding quiz for those tags, we cannot ensure that a member really know that skill which we want to achieve by the quiz system. Therefore, I think customized tag is not a good idea.
