### ISSUE TITLE
Tag suggestions

### ISSUE THREAD

**Issue by tsecheukyan1** [raymondlui719/teamform-seed#45]
As discussed in issue #40, we should provide a customized list of tags for users to choose from, but as I can think of little category of tags by myself, so maybe guys u can suggest some tags with its category and put it in firebase.
I would open a new list of tags(called newTags in firebase), I will delete the old one when the newTags is ready. Feel free to add tags with its category in the firebase(make sure u maintain the arrangement of list)

**Comment by cflamad** [comment]
I just found out that you are using the category name as the $id, would it be difficult to retrieve or manipulating the tags in your program(e.g. suppose a user selected C++ tag, can you do filtering easily by only referring to the string 'C++')? Also, would it be a problem if we change the tag name afterward?

**Comment by tsecheukyan1** [comment]
It would not be a problem , as classifying the category is only a mean to make the tag of list to be shown clearer to users, for functions, like searching or adding tags, we would not do any operations on the original full list of tags, and would only do operations on the parameter $scope.param.tags. Is it what ur concerning about?
