### ISSUE TITLE
How do we implement the tag system?

### ISSUE THREAD

**Issue by tsecheukyan1** [raymondlui719/teamform-seed#5]
I suggest team leaders to choose from list of tags when they start their team(should the lists of tags be stored in firebase database?).

**Comment by cflamad** [comment]
We should let them to write a short sentence to describe their team, e.g. which type of people they want. At the same time, we should provide them a list of tags such that other users can use the filter system to filter out some teams when they are finding teams.

The list of tags should added to firebase separately.

**Comment by tsecheukyan1** [comment]
I decided to put the list of tags in the js file directly, as it is more easily accessed.

**Comment by cflamad** [comment]
Mixing data and program in the same file is not a good way. Also the tags may be accessed in other features, you are better to store it in firebase.
