### ISSUE TITLE
rule of the ability test

### ISSUE THREAD

**Issue by ykcsteven** [raymondlui719/teamform-seed#64]
Would it be allowed that the member can do more than one time of the ability test? As member who fail the test may want to pass it, in order to get the tag of the ability, or the test can only do one time?

**Comment by cflamad** [comment]
I think you should add a date property to save when the user took the quiz and prevent them from redoing the quiz within a period of time(just say 1 month). As user may improve their skills in the future, it is better to let them redo the quiz after some time.
